Version 0.2 (#32)
* Revert "try new connection method"

This reverts commit d1bf8e3503fa08b1b773e82e0484a9d78184988d.

* wrap in with self.connect()

* Revert "wrap in with self.connect()"

This reverts commit 3ad664a9471c02f49a4d0606b8c149415bb84f66.

* use raw fetch

* debugging

* convert to str

* debugging temp change error message

* fix error handling

* fix comment indentation

* better error handling

* simpler reason message

* return after log

* fix table name

* delete tables on guild leave

* allow to specify just 'admins'

* try with fetch method

* remove where statement

* use raw to fetch all settings

* debugging db.fetch()

* debugging

* quote table names

* iterate through admins and print correctly

* rm debug log message

* switch to new fetch calling options

* unnecessary option

* fix var name

* quotes in proper places for sql query

* never return one for admins, thats dumb

* fixed db list gets overwritten

* actually add admins to message

* debugging

* show displayname and discriminator in admin list

* mention admins, instead of tryna get user

* make sure to remove the is-admin int thing

* iter thru list to rm 1s

* docstrings to describe options

* re-add try/except block in admin.add

* Revert "docstrings to describe options"

This reverts commit b356faca5f80d91cf46015fa8405ee66bfa40f35.

* changelog and grammar

* new linter

* fix linting process

* linting is not working with classes

* remove guild-specific vars

* functions in class need self

* uniform log message

* add modlog channel

* `/warn` command

* fix literal in if

* slash command

* make all slash commands and pass self

* fetch by id

* error handling

* better error handling

* await interaction.send

* error in var naming

* concatenate in func call

* error handling

* show usernames if not mentioning

* use SlashOption

* use dict

* convert manually to dict

* try raw bool

* forget SlashOption()

* bot, not client

* send just IDs

* fetch correctly

* newline after each list entry

* list polishing

* handle if user is non

* in debug, get type

* in debug, check if executor is in list

* simpler check for perms

* different id check

* try another check method

* fix setting naming

* when sending settings, dont send admin-specific values

* print to log

* dont attempt to send settings

* fixing verifying

* using raw cursor in verify

* debug logging and new repair method

* use self

* forgor to use self again

* error handling

* make sure to fetchall

* planning for new db function

* new verify function for db

* pass guild obj, not id

* settings: get settings

* list all settings, and load avail. in init

* await and send interaction

* use correct param name

* async

* remove bad log message

* use correct dict

* remove list option and parse settings output

* convert to str before parsing

* setting set

* also ignore ValueErrors

* ignore valueerror correctly

* update settings correctly

* polishing of set

* close db

* /announce command

* try with nextcord client

* roles are guild-specific

* remind user how to set custom values

* remove unnecessary spacing

* error handling and pass int

* get channel with self.bot()

* send interaction

* debug log

* put into separate ifs

* correct slashoption

* command description

* option description and type hinting

* import Optional

* make settings required

* debug log message

* put debug msg in right place

* roles are guild-specific, and must be fetched as such

* remove old verify function

* mention commands and channels in set response

* replace `\n` (string) in announcement with newline

* make rest of messagequote

* better announcement signature

* general improvements

* make messages match

* correct send

* use self

* remove debug log messages

* slash command `announce` has moved

* use self

* polishing of `/warn`

* TESTING_GUILD_ID cannot be self.

* use self for testing_guild_id

* load cfg outside of init for TESTING_GUILD_ID

* 'Interaction' object has no attribute 'user_id'

* replace() argument 2 must be str, not TypeError

* fix show_message

* make mod response ephemeral

* bot cant warn itself

* proper nomenclature

* polish report user

* correct nomenclature

* TypeError, not ValueError

* call db with guild, not id

* raise error and exit if called with id

* missing newline

* get modlog channel with guild method

* player reporting

* report bug

* proper naming

* naming again

* formatting syntax

* make error ephemeral

* use valueerror instead

* check bugreports_channel, not modlog

* remove extra parenthesis

* update changelog

* change code status description

* allow for custom tables

* refining custom db check

* polishing for custom tables

* `/ip` command

* config must be loaded seperately in function definition

* correct class name

* use more generic naming

* addrole command

* debugging, fixing defer()

* await add_roles()

* remove debug sleep

* fetch humans to give role to

* atomic, with reason

* debug guild.humans

* dont pass guild_ids to subcommand

* use members intent

* delete roles. and only defer if necessary

* dont check if they have the role

* use proper remove_roles function

* handle invalid role

* correct naming

* mod application

* better description, NameError

* `/apply` polish and final portions

* invovke db with guild object

* clarify channel ID

* correct setting name

* dont await get channel

* formatting

* formatting (quote block)

* Change LICENSE to BSD-3-Clause

* Documentation Changes (#18)

* guild settings docs

* fix name in log message

* cogs overview

* admin and announce cog docs

* applications and catboi docs

* fun and hello cog docs

* debug cog docs

* moderation cog docs

* reporting cog docs

* settings cog docs

* add db.close() method info

* tasks cog doc

* utilities cog docs

* add docs location

* start

* assign bools even if not used

* parse settings if mentioned

* strip, not trim

* move outside of if and before db.set()

* move try, removing redundency

* autocomplete settings

* correct arg usage

* strip instead of replace w/ ''

* strip value, not setting.

* parse other values

* no type warning when setting to 'none'

* documentation for type hinting

* remove TESTING_GUILD from slash command functions (#20)

* DM Guild owner on bot start, and add them to the admins list (#22)

* dm owner on guild join, and add them as an admin

* grammar

* rework lint action

* use db to fetch admins

* remove unnnecessary log message

* use self to fetch display name

* fetch perms from db in  `/admin rm`

* catch forbidden error, and tell user. (#23)

* Properly remove old guild data on guild leave (#24)

* debug -> success (more visible for debugging)

* switch to guild remove, not leave

* add success message on end

* success -> debug

* grammar and update roadmap

* Write contribution guidelines

* Minor changes (#25)

* Update Roadmap

* QoL improvements to cogs/fun.py (#26)

* remove unnecessary commented block

* add experimental auto-release for prod branch

* Add note regarting working dir of bot

* change note on security of root user

* Polish statup & guild join tasks (#28)

* dont run thru the settings-repair loop if intact

* verify DB after creation to ensure success

* close each DB connection on verification

* style guide for user-facing messages

* Moderation Suite and other Changes (#27)

* kick command

* description for user

* bugfix: check if existing in admin add

* bugfix: in admin rm (misspelling)

* bugfix: fetch admins correctly for checking existing in rm

* check for mod perms properly

* colon

* simple /info command

* spelling

* clarify timezone

* change is_mod method

* bugfix for message when there are no admins

* check correct message portion (in prev bugfix)

* fix conditional

* use interaction for channel fetch, and make error more concise

* catch just exception

* catch cannot dm, and option to not dm upon kick.

* return if could not DM

* get channel from interaction in kick

* actually kick them lol

* place common utility functions in separate file

* start moving moderation actions to libs/

* replace some functions with libs/ counterparts

* async/await

* remove functions now in libs

* specific log messages

* load config from yaml for utils, and refine utility.error_unexpected

* make moderation.kick, async

* use is_mod from libs.utility

* try fixing it with a lambda

* testing

* add reason to kick function def

* await kick()

* error_unexpected doesnt need to be async

* put error in quotes for log message for legibility

* switch to new usage of error_unexpected

* other method for getting bot user id

* working method to fetch ID

* nextcord commands are from ext

* send bot object in manually

* fetch id from new passed bot object

* await guild.kick

* add reason

* kick complete!

* add the tiramisu comment to database lib

* timeout lib function

* timeout discord command

* workaround nextcord typehint limitations

* change Optional[] to str

* add a cool startup log message

* remove unused `dm` option

* separate function for sending modlog messages

* fix undefined name user

* use new modlog function in timeout

* get channel from guild obj

* include reason in modlog

* underline keys in modlog message

* fix keys

* use new modlog func in kick

* add ban function

* touchup ban func

* add cool emojis to modlog

* remove 3month option from timeout (discord restriction)

* discord cant do timeouts > 1wj

* allow specifying delete messages days

* add ban command

* change delete_message_days to type int

* move welcome screen usage

* await modlog in ban

* change welcome screen message

* make ban command reply ephemeral

* add warn function to libs/moderation

* use new warn func in cogs.moderation

* use correct unexpected error function

* fix SlashOption parameter syntax

* pass correct bot user to warn

* correctly utilize modlog in warn

* add dependency caching to linting

* Add `/help` command (#30)

* Start adding help menu messages

* additional help topics

* add help command

* remove try/except block

* use correct key for help contents

* remove unnecessary newlines

* re-add try/except block

* update description for help command

* remove releases.yml.

decided its probably better to manually release.

* General Bugfixing (#31)

* polishing up options of admin commands

* fix imports

* more polishing for admin commands

* more refinements 🍷

* fix typehints

* so, that was not allowed

* ascii art in welcomescreen

* use tildes for icing line

* add utility func for type checking settings values

* add response for invalid setting

* utilize new version check in cogs.settings.setting.set

* fetch ID validity from guild instead

* sql injection prevention

* accept plaintext settings types

* update parity page

* update documentation

* remove whitespace

* make mod application response ephemeral

* properly get bot's display name

* remove unnecessary legacy code, and revert cogs actions to subcommands

* space out imports

* add neat comment at top of every file

* more tidying up of bot.py
- fix cogs list
- remove database committing on `/stop`
- send user ID in log who used `/stop`
- use exit code 0 on `/stop`

* fix log messages to match filename

* add more help topics

* update roadmap

* update code status

* make help messages ephemeral

* add view counter

* add lint workflow badge

* suggest using help on bot invite

* typo

---------

Co-authored-by: fizzdev <58730469+fizzrepo@users.noreply.github.com>